version: '3'
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.swoole
    ports:
      - 80:80
    environment:
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=80
      - GOROOT=/usr/local/go
      - GOPATH=/go
      - GOBIN=/go/bin

